
spring:
  mail:
    host: smtp.gmail.com
    username: mohamed.alaa32.msa@gmail.com
    password: sydz lezg mszg yejd
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true